#!/bin/sh
RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NOCOLOR='\033[0m' # No Color

echo ""
echo -e "${YELLOW}Building project...${NOCOLOR}"
    
DOTNET_CLI_TELEMETRY_OPTOUT=1
DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

cd src/

dotnet build

if [ $? -ne 0 ] ; then
    echo ""
	echo -e "${RED}Build failed. Please correct the problems before proceeding${NOCOLOR}"
	echo ""
	exit 1
fi

echo ""
echo -e "${YELLOW}Running unit tests...${NOCOLOR}"
echo ""
	
cd ../tests/UnitTests

dotnet test

if [ $? -ne 0 ] ; then
    echo ""
	echo -e "${RED}One or more unit tests failed. Please correct them before uploading changes${NOCOLOR}"
	echo ""
	exit 1
fi

echo ""
echo -e "${YELLOW}Running functional tests...${NOCOLOR}"
echo ""

cd ../Functional/Tests

dotnet test

if [ $? -ne 0 ] ; then
    echo ""
	echo -e "${RED}One or more unit tests failed. Please correct them before uploading changes${NOCOLOR}"
	echo ""
	exit 1
fi

echo ""
echo -e "${GREEN}Pre push completed. Everything is OK${NOCOLOR}"
echo ""

exit 0