services:
  avatarize-api:
    container_name: avatarize-api
    build:
      context: .
      dockerfile: ./src/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5105:5105"
      - "7152:7152"