services:
  avatarize-api:
    container_name: avatarize-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "50002:50002"
      - "50003:50003"