name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SCRIPT_AFTER: |
            whoami
            ls -al
            dotnet restore "./src/Avatarize.csproj" --disable-parallel
            dotnet publish "./src/Avatarize.csproj" -c Release -o /app --no-restore --self-contained true --os linux
            export ASPNETCORE_URLS=http://*:80 
            dotnet ./src/app/Avatarize.dll